-- شغّل هذا الملف في Supabase > SQL Editor
create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  civil_id text not null unique,
  name text not null,
  school text,
  specialty text,
  status text default 'مرشح',
  message text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.candidates enable row level security;

-- لا تسمح بقراءة الجدول مباشرة من الزوار.
drop policy if exists "admin read candidates" on public.candidates;
drop policy if exists "admin insert candidates" on public.candidates;
drop policy if exists "admin update candidates" on public.candidates;
drop policy if exists "admin delete candidates" on public.candidates;

create policy "admin read candidates" on public.candidates for select
to authenticated using (true);
create policy "admin insert candidates" on public.candidates for insert
to authenticated with check (true);
create policy "admin update candidates" on public.candidates for update
to authenticated using (true) with check (true);
create policy "admin delete candidates" on public.candidates for delete
to authenticated using (true);

-- دالة الاستعلام العامة: تعيد البيانات المسموح عرضها فقط.
create or replace function public.lookup_candidate(p_civil_id text)
returns table(name text, school text, specialty text, status text, message text)
language sql
security definer
set search_path = public
as $$
  select c.name, c.school, c.specialty, c.status, c.message
  from public.candidates c
  where c.civil_id = regexp_replace(p_civil_id, '\D', '', 'g')
  limit 1;
$$;

revoke all on function public.lookup_candidate(text) from public;
grant execute on function public.lookup_candidate(text) to anon, authenticated;

-- بعد إنشاء أول مستخدم إداري من Authentication > Users،
-- يمكنه الدخول إلى /admin وإدارة البيانات.
